### ISSUE TITLE
Question about chamfer evaluation

### ISSUE THREAD

**Issue by xiaomingjie** [jackd/template_ffd#7] opened 2018-06-01 08:15 UTC
Hi @jackd ,

I used your data as the input of PSGN, and I got 0.00039 chamfer distance with test split of plane in PSGN, while got 0.031 in your work. At the same time, the author of DN got 0.14 in PSGN according to their paper. I suppose that the results rely on different evaluating methods, so I tried to use your chamfer calculating method in PSGN.

I suppose that your method is `np_metrics.chamfer(c0,c1)/n_samples` in `template_ffd.metrics` while c0, c1 are np arrays of GT point clouds and infered point cloud. So I added this line in PSGN but it didn't get the correct result.

`dis=np_metrics.chamfer(pred,pt_gt.eval())/1024`

here pred is an np array and pt_gt is a tensor.

I also tried `tf_metrics.chamfer` but got `AttributeError: 'tuple' object has no attribute 'as_list'`. I looked into your implement and found it was similar to nn_distance of PSGN so I was wondering why I used got inappropriate results in PSGN

plane has 803 test example but when it iterate to 400 and it got me an `OutOfRangeError`. And the result of the first 400 examples still are strange like 0.0041 because it is supposed to be 0.14..

So could you tell me how to use your chamfer metrics? 

Thanks a lot!

**Comment by jackd** [comment] 2018-06-01 13:14
There's some weird point cloud rescaling that has to be done. Minimal bounding half-sphere with radius 10 or something, but I'm going from memory and not at my desk. The numbers in the paper are the chamfer distances after rescaling. Maybe check eval/normalisation.py or something? Will check in morning...

**Comment by xiaomingjie** [comment] 2018-06-01 13:21
I know that you scale CD by 1000x and I have turned it back to original scale like I said above. The point is why got so low values in PSGN with your data and without any other changes about PSGN. 
And I am looking forward to your reply. Thanks!

**Comment by jackd** [comment] 2018-06-01 13:28
Have you transformed the clouds by the calculated normalisation parameters before you take the chamfer distance? This has nothing to do with the 1000x, that was just for readability

**Comment by xiaomingjie** [comment] 2018-06-01 13:31
Emmm, actually I don't know where normalisation parameters are and just use `get_predict_input` directly.

**Comment by jackd** [comment] 2018-06-01 13:37
Nothing to do with the input. The numbers from the paper are the result of chamfer distancing a transformed ground truth/inferred cloud. PSGN did that to make their numbers comparable to a voxel method, and we did it to make ours comparable to them and deformnet. If I've misinterpreted it I'd like to know - the numbers do look suspiciously like a factor of 4 difference, which could be down to a scaling factor of 2 error, but I confirmed with deformnet authors a few points before putting the paper up, and to the best of my knowledge Ive done the same transformation as them (which they claim is the same as psgn... But if you read the psgn paper it's a bit cryptic).

**Comment by xiaomingjie** [comment] 2018-06-01 13:48
According to DN paper, it should be 0.14 instead of 0.00039 and I can't tell what the similarity is between them.. I looked into your nn_distance too and I think your implementation is the same as PSGN. That really confuses me why so different are the results.. If you are free I would be very grateful to discuss with you and try to figure it out next morning or some time else.

**Comment by jackd** [comment] 2018-06-01 23:01
Put up some code/data somewhere and I'll take a look.

**Comment by xiaomingjie** [comment] 2018-06-02 00:39
I've put code [here](https://github.com/seanmj/PSGN/blob/master/depthestimate/train_nn.py). I used your data and your `builder` class for data operation. If you would like to run the code, I also put in tf_nndistance_so.so and makefile but you need to edit makefile like change directions. Actually to run PSGN code, especially to compile .cpp is really annoying due to different development environment. I suppose that you use the same nn_distance as tf_nndistance, so you can use your complied and used nn_distance in your code instead of tf_nndistance.

**Comment by jackd** [comment] 2018-06-02 01:23
The only thing I intended to be similar to PSGN is the input images and the evaluation scheme. You're not using my metrics or evaluation scheme, and I don't particularly feel like hacking through 400 lines of your code.

See `eval/normalize.py` for normalization procedure. If you have ground truth vertices, ground truth cloud and inferred cloud as numpy arrays for a single example it should look something like the following:

```python
from template_ffd.eval.normalize import get_normalization_params, normalized
from template_ffd.metrics import np_metrics

def get_example_chamfer_metric_for_table(gt_vertices, gt_cloud, inf_cloud):
    assert(len(vertices.shape) == 2)  # single example
    assert(gt_cloud.shape[0] == inf_cloud.shape[0])
    offset, scale = get_normalization_params(gt_vertices)
    gt_cloud = normalized(gt_cloud, offset, scale)
    inf_cloud = normalized(inf_cloud, offset, scale)
    return np_metrics.chamfer(gt_cloud, inf_cloud) / gt_cloud.shape[0]
```

**Comment by xiaomingjie** [comment] 2018-06-02 01:43
Yeah, I did not use your evaluation scheme for CD and I am trying to do that. I will try this normalize function to see what will happen. I suppose you mean this in your reply..
`gt_cloud = normalized(gt_cloud, offset, scale)`

And as for my code there, I think the only matter thing about CD is `dists_forward,_,dists_backward,_=tf_nndistance.nn_distance(pt_gt,x)`
where pt_gt is gt_cloud and x is inf_cloud. nn_distance here may be similar to your nn_distance.
then CD = dists_forward + dist_backward and it got 0.00039 in plane..

**Comment by jackd** [comment] 2018-06-02 01:58
You calculate the offset and scale based on the vertices of the cad model.

PSGN preprocess their data, I post-process. Last paragraph before 5.2 in their paper. unit1 = 3.2 from what I can tell/confirmed with deformnet authors.

**Comment by xiaomingjie** [comment] 2018-06-02 02:13
So I suppose you mean that different normalization operation of dataset between you and PSGN makes that happen. If I would like to use your data in PSGN's metrics then I should turn your data to their form first. I will try that first.

However I would like to use your metrics (which I suppose that DN uses this metrics to get their result) too.  I used your `np_metrics.chamfer` at the same time like I said in first post at this issue. Plane has 803 test example but when it iterate to 400 and it got me an `OutOfRangeError`. And the result of the first 400 examples still are strange like 0.0041 because it is supposed to be 0.14..

**Comment by jackd** [comment] 2018-06-02 02:27
If you give me a *minimal* working example which causes the `OutOfRangeError` I'll look into it.

If you evaluate on a dataset with a different normalization scheme, don't expect the same results unless you renormalize. I don't know how to say this more clearly. I use the standard normalization provided by shapenet (unit bounding box centred at origin), they convert to a minimally bounding hemisphere of radius 3.2. I'd be very surprised if there's a difference between the results of the different `chamfer` implementations, but if you feed differently scaled models in, you'll get differently scaled values out.

**Comment by xiaomingjie** [comment] 2018-06-02 02:54
OK I got it and thanks for your patient answer.

I think it's hard to give a minimal woring example since inf_cloud relies on the whole network..

But I can tell that I get gt_cloud with 1024 points using `builder.get_predict_inputs()` and I get inf_cloud with also 1024 points from network output. Then I use code below after every sess.run iteration

```
distance = np_metrics.chamfer(gt_cloud, inf_cloud) 
value.append(distance)                #value=[] at first
```

**Comment by xiaomingjie** [comment] 2018-06-02 05:44
I've added `get_example_chamfer_metric_for_table` and got another CD 0.036 still not closed to 0.14. When I run this function my cpu and mem both achieve 100% usage. And it takes me two more minites while it used to be few seconds before using this function. My code is below and I think this time I use your metrics to calculate CD instead of PSGN's metrics.

```
mesh_ds=get_mesh_dataset(cat_id).subset(example_ids)
    with mesh_ds:
        for example_id in example_ids:
            mesh=mesh_ds[example_id]
            gt_vertices,faces= (np.array(mesh[k]) for k in ('vertices','faces'))
        ......
with tf.Session(config=config) as sess:
        ......
        for i in xrange(0,length)
              .....sess.run.....
        assert(len(gt_vertices.shape) == 2)  # single example
        assert(gt_pt.shape[0] == pred.shape[0])
        offset, scale = get_normalization_params(gt_vertices)
        gt_cloud = normalized(gt_cloud, offset, scale)
        inf_cloud = normalized(inf_cloud, offset, scale)
        res=np_metrics.chamfer(gt_cloud, inf_cloud) / gt_cloud.shape[0]
        print np.mean(res)
```

**Comment by jackd** [comment] 2018-06-02 06:54
1. If you want me to look at your code, give me a minimal working example. Your first link might work, but it wasn't minimal. Your latest response is closer to minimal, but it definitely isn't working. If you need something which is the output of a complicated function, save the results of that complicated function, refactor the code to work with the loaded version, and make the data available somewhere along with the code.
2.The values I report for the other methods were from their papers, or attributed to their papers by others. I do not reproduce the results of every paper I compare against.
3. The numbers I report for my method are based on the descriptions given in other papers. I have done my best to faithfully reproduce their evaluation scheme. If you can identify a discrepancy between what PSGN/deformnets discuss in their paper and my evaluation scheme, I'm happy to investigate. That said, there are many possible reasons why your numbers are not the same as those reported, and I'm not going to debug your code base to try and understand why.
4. If you believe there is a discrepancy between what the authors of PSGN say in their paper and what they implement in their code, that is something you should raise with them.
5. There are slight differences in the dataset - most notably, my models were trained with a single view, while PSGN/deformnet trained with a random view from multiple. PSGN also trained a single model across all categories, unlike mine. These have both been addressed in the dev branch, but there's probably still bugs there and I won't be addressing issues there until I merge it back into master. In short, the results of the method in here drop sligthly, but not significantly - ~20% to chamfer loss.

**Comment by xiaomingjie** [comment] 2018-06-02 07:37
I will try to give a minimal working example. 
I am just curious that  why the same dataset with same scale and same metrics didn't get absolute CD, which means I have to compare in relative CD. But this is my work and I have bothered you too much so far lol. Maybe I should check with the author of DN that how they get CD of PSGN..
I will keep going and looking forward to your amazing work in the future. Thanks again.

**Comment by jackd** [comment] 2018-06-02 08:20
PSGN wanted to compare against a voxel method, so they did some weird rescaling.

From an email correspondence with Andrey Kurenkov, DN lead author:

Hi Dominic,

That normalization looks right to me. We don't plan to release the code, but I can send along the relevant bit:


distsA,idxA,distsB,idxB = nndist.nn_distance(rescaled_gt,rescaled_def)
rescaled_cd_losses_op = tf.reduce_sum(distsA,1)/self.n_pts+tf.reduce_sum(distsB,1)/self.n_pts#loss of all batches
...
rescaled_def_points = data['in_pts']-self.v_size/2
#points are centered at n_vox/2, move back to center at origin
rescaled_gt_points = data['gt_pts']-self.v_size/2

min_batches_z = np.amin(rescaled_gt_points[:,:,1],axis=1)#Z axis is index 1, not 2
rescaled_gt_points[:,:,1]-=np.repeat(min_batches_z[:,np.newaxis],n_pts,1)
min_batches_z = np.amin(rescaled_def_points[:,:,1],axis=1)#Z axis is index 1, not 2
rescaled_def_points[:,:,1]-=np.repeat(min_batches_z[:,np.newaxis],n_pts,1)

max_batch_dists = np.sqrt(np.amax(np.sum(rescaled_gt_points**2,axis=2),axis=1))#get max dists from origin

for b in range(self.batch_size):
rescaled_gt_points[b]/=max_batch_dists[b]
rescaled_def_points[b]/=max_batch_dists[b]
rescaled_gt_points[b]*=3.2
rescaled_def_points[b]*=3.2

if cfg.TEST.EVAL_EMD:
cd_losses,emd_loss = self.sess.run([rescaled_cd_losses_op,emd_loss_op],
   feed_dict={rescaled_gt: rescaled_gt_points,
  rescaled_def: rescaled_def_points})
else:
cd_losses = self.sess.run(rescaled_cd_losses_op,
   feed_dict={rescaled_gt: rescaled_gt_points,
  rescaled_def: rescaled_def_points})
emd_loss = 0
losses = cd_losses

loss_value = np.mean(cd_losses)


Hope that helps.

**Comment by xiaomingjie** [comment] 2018-06-02 09:09
Thanks for sharing these info. I will see what I can do to fix the result.

**Comment by xiaomingjie** [comment] 2018-06-04 06:20
Maybe I got something wrong last time..Here is my confusion
`normalized(points,offset,scale)`
what shapes are they here in your original implement?
My points is [803,1,1024,3], offset is [803,3], scale is [803] cause plane has 803 examples.

**Comment by jackd** [comment] 2018-06-04 06:30
It was written to be used with a single point cloud - so `points.shape == (n_points, 3)`, `offset.shape == (3,)`, `scale.shape == ()` (or just a scalar). You could get away with `(n, n_points, 3), `(n, 1, 3)` and `(n, 1, 1)` if you wanted.

**Comment by xiaomingjie** [comment] 2018-06-04 06:32
got it!

**Comment by xiaomingjie** [comment] 2018-06-04 09:12
I put a minimal working example [here](https://github.com/seanmj/PSGN/tree/master/example).
`gt_cloud`s are from your point cloud data 'plane'. `inf_cloud`s are inferred from PSGN. `scale` and `offset `are from `get_nomalization_params_dataset`. I think this is the same normalization as you and DN but it seems to get a 'much more' better result like 0.023 which I think I am still wrong somewhere.

**Comment by jackd** [comment] 2018-06-04 10:59
(using my `util3d` repo for visualising)
```python
import numpy as np
from template_ffd.eval.normalize import normalized
from mayavi import mlab
from util3d.mayavi_vis import vis_point_cloud

gt_cloud = np.load("gt_cloud.npy")
inf_cloud = np.load("inf_cloud.npy")
gt_cloud = np.squeeze(gt_cloud, axis=1)
inf_cloud = np.squeeze(inf_cloud, axis=1)

scale = np.load("scale.npy")
offset = np.load("offset.npy")

gt_cloud = np.array([normalized(gt, o, s) for gt, o, s in zip(
                gt_cloud, offset, scale)])
inf_cloud = np.array([normalized(gt, o, s) for gt, o, s in zip(
                inf_cloud, offset, scale)])

sphere = np.random.normal(size=(1024, 3))
sphere *= 3.2/np.linalg.norm(sphere, axis=-1, keepdims=True)
sphere[sphere[:, 1] < 0] *= -1

for gt, inf in zip(gt_cloud, inf_cloud):
    vis_point_cloud(gt, scale_factor=0.05, color=(0, 1, 0))
    vis_point_cloud(inf, scale_factor=0.05, color=(0, 0, 1))
    vis_point_cloud(sphere, scale_factor=0.05, color=(1, 0, 0))
    mlab.show()
```

blue/green: normalized inferred/ground truth clouds
red: hemisphere of radius 3.2 (= unit 1 = 32 / 10, where 32 is the grid size of r2n2)

If you can suggest a more accurate interpretation of "we normalized the radius of its bounding hemi-sphere to unit 1 and aligned their ground plane" I'm all ears.

Numbers in our paper are from DN and seem consistent with the average reported by PSGN.

I cannot explain the discreprency in the results for sure. Possible explanations:
* different normalization scheme. Again, looking at the results of above, I honestly believe the one we/DN chose was consistent with the explanation given in PSGN.
* train/test data mix up. I haven't seen exactly how you generated those numbers (I can guess, and if you did it how I guess I can't see anything wrong with it). A small change in the script (e.g. training on the test data) at some point in the past then fixing the script is impossible for me to tell. Not suggesting you did this intentionally - just that these things happen in fast iteration/dirty code environments.
* PSGN gets incredibly good results when you train/evaluate on a single category, compared to multi-category training. I'd expect it to get slightly better, but nothing as significant as this. Our own results showed a modest decrease in performance when trained over 13 categories - up to 50% in some case - but ours was never really designed to run across multiple categories, so I'd expect the difference in PSGN to be less.

Side note: I noticed you're using `loss_nodecay=(dists_forward+dists_backward/2.0)`, as is the original repo. That's not a chamfer loss. Not sure if this is intentional, and it probably won't affect the results too much, just pointing it out.

**Comment by xiaomingjie** [comment] 2018-06-04 11:24
The whole points won't beyond a hemi-sphere. So in the horizontal direction, the farthest two points should be in 6.4 and in the vertical direction the distance between the farthest point and the center should be no more than 3.2. I think this is it and we all know that..

So the normalization scheme is the same, I will go check on my training and I think I just used `get_train_inputs` to train the network and `get_predict_inputs` to evaluate the results while you already split train/test set. However I will try to train more later.

As for loss_nodecay, it's what it is in the original PSGN. I supposed that it''s a trick which they didn't mention in their paper and it indeed improved the performance slightly.

Thank you for your reply! I will keep fixing it.

**Comment by xiaomingjie** [comment] 2018-06-05 02:23
I've trained more times and it got the same results like lower a magnitude(0.023) than it should be(0.14).
I used `get_train_inputs` from builder while training and `get_predict_inputs` while testing so I think I did not mix up the train and test data.. And while training after 50000 iterations, train loss is like 0.00028(without normalization here while test loss is 0.00039 at last without normalization), so that I think training went well but got wrong answer..

Another thing is when you said about the average reported by PSGN,  I ran their code which only has training datastet and got 0.0044 CD after 300,000 iteration so that's the train loss without normalization. If I got 0.0021 not 0.00021 in plane training data so that I can say I am closed to them

I noticed another paper we both read [here](https://arxiv.org/pdf/1706.07036.pdf). It's a little earlier than DN and in Table 3 before Sec 4.2, the result of plane from this paper shows 0.028.. It's really weird..

**Comment by xiaomingjie** [comment] 2018-06-08 03:42
Hi @jackd ,

I think I got the latest results here. I use PSGN's network in your code but without using template_ffd. I got 0.028 after 100,000 iteration which is similar to results of [Dense Point Clouds](https://arxiv.org/pdf/1706.07036.pdf)

Here is my conclusion. Training in a single category will get much better results than training in multiple categories. DN said that they use "the newest trained model released by PSGN", which I suppose that it means the model [here](https://github.com/fanhqme/PointSetGeneration) ([twobranch_2.pkl](https://drive.google.com/file/d/0B0gQFbJEIJ4kUTc2cGlDeDh6VGs/view) is the latest one that PSGN released) is trained in multiple categories with data of PSGN's own dataset [PointSetGeneration220K](https://www.dropbox.com/sh/68kfpqut2y75etz/AABtIn2LUMALTnULSTUr5ZlUa?dl=0) while the results of Dense Point Clouds are more like training in single category.

Here is the CD of plane.

```
DN       PSGN(published by DN)     PSGN(published byDPC)        my result of PSGN (both on original PSGN and your code with PSGN's network without ffd)
0.10              0.14                0.028                          0.0278(100,000 iter)
```

That's my personal experiment and no offence to any other opinions and just sharing my point here.

I'm sorry to border you so much these days. But if this result interested you, I will be happy to continue do more with you.

Thanks a lot!

**Comment by jackd** [comment] 2018-06-08 05:53
Interesting. It surprises me to see -that- much of an improvement. We went the other way recently - changed from a single category to 13 - and got a modest performance downgrade - but around the 50% mark, rather than 400% mark. Maybe planes are an exceptional case? There's significantly less variation - at least topologically - in planes compared to others, like chairs.

If you want to run more experiments with multiple categories and multiple views and my data feel free to check out the dev branch. I'm balls deep in other projects right now so haven't been able to clean up a few things here and there (hence haven't merged back into master) but you should be able to use the input pipeline (and training/chamfer evaluation). Just make a params file with a list for cat_desc and/or list for view_index, e.g.
```json
{
 ...
 "cat_desc": ["plane", "car", ...],
 "view_index": [0, 1, 2, 3, 4, 5, 6, 7]
}
```

View indices can be anything in `range(0, 8)`.

**Comment by xiaomingjie** [comment] 2018-06-08 06:30
Thanks!
I will keep training in other categories and see what will happen.

**Comment by jackd** [comment] 2018-08-14 02:15
Closing this, because it doesn't seem to be an issue with this repo. Feel free to reopen if there are developments.

**Closed as completed by jackd** 2018-08-14 02:15 UTC
