### ISSUE TITLE
can't find where the CD was calculated..

### ISSUE THREAD

**Issue by xiaomingjie** [jackd/template_ffd#4] opened 2018-05-18 03:41 UTC
Hi @jackd,
I firstly went through the training pipiline in `scripts/train.py` and so far so good to understand it.
But when I tried to do the same thing in `scripts/chamfer.py`, it didn't go well..

it seems that `eval.chamfer.report_chamfer_average()` directly get the final json file which includes {example_id : CD_value} in it. I know that `get_saving_dataset` or `get_saved_dataset` should lead me to where the prediction and the GT are saved and where they get calculated, but I really can't find when I jumped between .py here and there. Would you give me some help?

Another question I have is that CD should have been defined in d(GT(16384)->PRED(1024)) + d(PRED(1024)->GT(16384)) in PSGN and your paper. I wonder if you use 1024 points to resample GT will affect the results.
But after I tried it, I got 0.031 in resample 1024 points but got 0.016 in resample 16384 for model plane. I think that it's weird and still working on figuring out what happened and then I am stuck on reading chamfer.py...

**Comment by jackd** [comment] 2018-05-18 03:59
The saving/saved datasets are responsible for (surprisingly enough) saving the data, and loading anything that's been saved before. Originally, this data comes from the lazy dataset defined in `get_lazy_dataset`. This just takes the sampled ground truth/inferred clouds and maps them through `np_metrics.chamfer`.

I confirmed with the authors of the [other paper](https://arxiv.org/pdf/1708.04672.pdf) that I used the same average CD as them (as opposed to the total sum), and they had reproduced the work of PSGN. I suppose we might both have misinterpreted the PSGN paper, and that approach achieved 250x as good a result as us... but I find that less likely.

Since this is an average chamfer loss, more points will likely reduce the value. The values reported by default and in the paper are for 1024 points in each cloud. Note if you use a different number of points in each cloud you'll have to change my implementation slightly since I just divide the sum of both chamfer loss terms by the number of points in the inferred cloud.

**Comment by xiaomingjie** [comment] 2018-05-18 04:30
Yeah, I also read relevant functions like `get_lazy_dataset` which had defined in two certain classes in `eval/chamfer.py`, but I still don't know where in `scripts/chamfer.py ` or `eval/chamfer.py` calls it. As for `np_metrics.chamfer`, I nearly can't find where it shows..

As you said, you divide the sum by the number of points in the inferred cloud. So did i misunderstand the argument `scripts/chamfer.py -n 16384` ? So this n_sample is for the inferred point cloud not the GT point cloud? If i was wrong, then how can I resample GT by 16384 points or don't do the resampling just remaining GT's 16384 points?

**Comment by jackd** [comment] 2018-05-18 05:35
The `-n` flag applies to both ground truth and inferred clouds. The code isn't currently set up to allow for a different number of points between clouds. It wouldn't be -that- hard to change to allow for it, but unless there's demand for it I'd rather keep it simple.

`get_lazy_dataset` produces a lazy dataset that is the result of mapping an evaluation dataset (an inferred cloud and the ground truth cloud transformed to the appropriate reference frame) to a chamfer loss.

**Comment by xiaomingjie** [comment] 2018-05-18 05:52
All right I got you, I will keep looking into the n_sample.
About `get_lazy_dataset` , I think you didn't catch me... I probably know what it does but don't know which function in `chamfer.py` calls it... Without a call, how can it launch to get a lazy dataset . I can see just  `get_saving_dataset` or `get_saved_dataset` in `chamfer.py`.  Then  `get_saving_dataset` leads to blablabla, it's hard to find who calls i`get_lazy_dataset` in where..

**Comment by jackd** [comment] 2018-05-18 07:22
Ah, right. That particular piece of API design was done rather close to the paper deadline. As mentioned, I need a better way of doing all this autosaving dataset stuff...

`SavingDataset`s are responsible for saving existing datasets, or loading pre-saved data. They have no way of creating the data on their own. `get_saved_dataset` first creates a lazy dataset with the required data, saves it to a `SavingDataset`, then returns the `SavingDataset`.

**Comment by jackd** [comment] 2018-05-20 02:44
Closing. I'll ponder a better AutoSaving interface for `dids`, but that's more an issue for that repo...

**Closed as completed by jackd** 2018-05-20 02:44 UTC
